# Generated by Django 5.2.5 on 2025-08-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('destino', models.CharField(max_length=150)),
                ('fecha_viaje', models.DateField(blank=True, null=True)),
                ('cantidad_personas', models.PositiveIntegerField(default=1)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
