# Generated by Django 5.0 on 2025-08-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_delete_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_pedidos'),
        ),
    ]
